apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: my-python-fn
  namespace: justeh
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: my-python-fn
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/justeh/python-functions-accelerator.git